name: Test run v1

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Show environment v1
        run: env | grep ^GITHUB
      - name: Show ref v1
        run: echo "===============> Version from $GITHUB_REF"
      - name: Show other ref
        run: echo "================> other version ${{github.ref_name}}
